### ISSUE TITLE
Does not compile - please add a note in the

### ISSUE THREAD

**Issue by anborg** [adeelibr/deno-playground#2]
https://www.freecodecamp.org/news/create-a-todo-api-in-deno-written-by-a-guy-coming-from-node/

The project does not compile

TS2339 [ERROR]: Property 'secure' does not exist on type 'ApplicationErrorEvent<Record<string, any>>'.
app.addEventListener("listen", ({ secure, hostname, port }) => {
                                  ~~~~~~
    at file:///Volumes/data01/projects/projects_js/learn-deno/learn_oak/deno-playground/chapter_1:oak/server.ts:24:35

TS2339 [ERROR]: Property 'hostname' does not exist on type 'ApplicationErrorEvent<Record<string, any>>'.
app.addEventListener("listen", ({ secure, hostname, port }) => {
                                          ~~~~~~~~
    at file:///Volumes/data01/projects/projects_js/learn-deno/learn_oak/deno-playground/chapter_1:oak/server.ts:24:43

TS2339 [ERROR]: Property 'port' does not exist on type 'ApplicationErrorEvent<Record<string, any>>'.
app.addEventListener("listen", ({ secure, hostname, port }) => {
                                                    ~~~~
    at file:///Volumes/data01/projects/projects_js/learn-deno/learn_oak/deno-playground/chapter_1:oak/server.ts:24:53

Found 4 errors.

**Comment by adeelibr** [comment]
Hi @anborg thank you for taking the time out to report an issue. Can you share a reproduction of this error maybe in a form of repository. So I can verify that.

**Comment by adeelibr** [comment]
close issue, because it is inactive
