### ISSUE TITLE
Chapter 1: createTodo does not set `todo` value

### ISSUE THREAD

**Issue by michaelachrisco** [adeelibr/deno-playground#3]
On default, when a user adds the following into postman:
```json
{
    "todo": "eat a lama"
}
```
![image](https://user-images.githubusercontent.com/398491/89369781-f0fefa00-d693-11ea-85ea-2e2b3ffa5c35.png)

The following result does not contain the new todo item.
```json
{
    "success": true,
    "data": [
        {
            "id": "53706530-3930-4ecd-9933-09de0c54388c",
            "todo": "walk dog",
            "isCompleted": true
        },
        {
            "id": "23462078-3a14-44ee-a161-7e56d805b901",
            "todo": "eat food",
            "isCompleted": false
        },
        {
            "id": "d9b3ff7a-1fc9-40dc-b12f-b10a89f1d212",
            "todo": "exercise",
            "isCompleted": true
        },
        {
            "id": "cf00b251-3adc-4b73-b3ec-3d6ba580f9ed",
            "todo": "read a book",
            "isCompleted": false
        },
        {
            "id": "795accc2-706b-4083-8c89-2233de0a2c09",
            "isCompleted": false
        }
    ]
}
```

**Comment by chansdad** [comment]
Merge the commit by @michaelachrisco  , also update the tutorial , so it will save others  a lot of time. This is a great starter tutorial for Dino .

**Comment by Lumca** [comment]
it works, but the way it was done in the tutorial makes sense. Why is it not working?

**Comment by chansdad** [comment]
@Lumca  got to do with the deno versioning i think, this tutorial is base don older version of deno i think

**Comment by michaelachrisco** [comment]
Closing this out. I think the repo is dead.
